### PR TITLE
Various fixes and refactoring

### LINKED ISSUE #71: Database triggers don't work for batch inserts
* pro `answers` bud nemuzeme pouzit trigger, nebo vyhodit batch 
```
05/03/2021 15:13:11 [DEBUG] [ce4b3595-7f7c-7f53-efa2-55db0d3f07a6] Exposed - INSERT INTO patients (email, first_name, id, insurance_company, last_name, personal_number, phone_number, updated) VALUES ('john@doe.com', 'John', 'e292d01d-cf08-49ee-b383-ae79255f0cfe', 'RBP', 'Doe', '7401040020', '+420123456789', NULL)
05/03/2021 15:13:11 [ERROR] [ce4b3595-7f7c-7f53-efa2-55db0d3f07a6] b.mild.covid.vaxx.ExceptionHandler - Exception occurred in the application: Can't add a new batch because columns: answers.created don't have default values. DB defaults don't support in batch inserts
org.jetbrains.exposed.sql.statements.BatchDataInconsistentException: Can't add a new batch because columns: answers.created don't have default values. DB defaults don't support in batch inserts
```

```bash
curl 'https://covid-vaxx.stg.mild.blue/api/patient' \
  -H 'content-type: application/json' \
  --data-raw '{"answers":[{"questionId":"9a5587a1-dc43-49f3-9847-b736127c9e39","value":"true"},{"questionId":"f74ebe1e-ef94-4af0-963d-97ffab086b6b","value":"true"},{"questionId":"f68d221d-27a1-4c81-bf45-07b1f0290e15","value":"false"},{"questionId":"f9c99047-0f44-4dfe-9964-71274a7af5e9","value":"false"},{"questionId":"f5cf0689-a4d7-4c42-8107-6eaedca88a93","value":"true"},{"questionId":"7b02b12a-abb4-45d3-8bf4-0b074e445f37","value":"false"},{"questionId":"112f5fbd-cde2-4fe9-8cab-f5b4fff57296","value":"true"},{"questionId":"f4ca8d25-faaa-4b2f-abc2-3d7a8702d4a3","value":"true"}],"confirmation":{"covid19VaccinationAgreement":true,"healthStateDisclosureConfirmation":true},"firstName":"John","lastName":"Doe","personalNumber":"7401040020","insuranceCompany":"RBP","phoneNumber":"+420123456789","email":"john@doe.com"}' \
  --compressed
```

### PR DESCRIPTION
**Pull request by LukasForst**
* closes #71 
* backend support pro #62

### CODE REVIEW

File: backend/src/main/kotlin/blue/mild/covid/vaxx/dao/Patient.kt [hunk 1]
```diff
@@ -8,7 +8,7 @@ import java.time.Instant
 object Patient : Table("patients") {
     val id = varchar("id", 36)
     val created: Column<Instant> = timestamp("created")
-    val updated: Column<Instant?> = timestamp("updated").nullable()
+    val updated: Column<Instant> = timestamp("updated")
```
Comment (marazt) [inline backend/src/main/kotlin/blue/mild/covid/vaxx/dao/Patient.kt:11]: Bacha, v migraci je update nullable. Ale tak to kdyztak zmenme na NOT NULL.

Comment (LukasForst) [reply backend/src/main/kotlin/blue/mild/covid/vaxx/dao/Patient.kt:11]: fixed v #78

**Review by marazt — APPROVED** [review]
